# Generated by Django 5.0.4 on 2024-04-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
